data_dir: data/fer2013
img_size: 48
batch_size: 64
epochs: 30
lr: 0.001
num_classes: 8
seed: 42

# configs/config.yaml
# TR: Notebook kodunun script yapısı için config
# EN: Config for converting the notebook code into scripts

data:
  data_dir: "./fer2013"
  img_size: [48, 48]
  batch_size: 64
  seed: 123
  val_split: 0.2

paths:
  models_dir: "./models"
  results_dir: "./outputs"
  best_model_name: "best_emotion_model_8class.keras"
  final_model_name: "final_emotion_model_8class.keras"

model:
  input_shape: [48, 48, 1]
  num_classes: 8

  # TR: Overfitting azaltma için Dropout artırılabilir
  # EN: Increase dropout to reduce overfitting
  dropout: 0.40

augmentation:
  # TR: Daha güçlü augmentation (Fear/Disgust için faydalı olabilir)
  # EN: Stronger augmentation (can help Fear/Disgust)
  enable: true
  rotation: 0.10
  zoom: 0.10
  contrast: 0.10
  translation: 0.08

training:
  # TR: Daha az epoch + EarlyStopping (overfitting azaltma)
  # EN: Fewer epochs + EarlyStopping (reduce overfitting)
  epochs: 30
  learning_rate: 0.001
  min_lr: 0.00001
  reduce_lr_patience: 5

  use_early_stopping: true
  early_stopping_patience: 8

  # TR: Class imbalance için: class_weight veya focal loss
  # EN: For class imbalance: class_weight or focal loss
  use_class_weight: true
  loss: "focal"       # "categorical_crossentropy" or "focal"
  focal_gamma: 2.0

  quick_test_eval: true
